/* The following code was generated by JFlex 1.2.2 on 10/11/13 16:22 */

/*******************************************************************************
 * Copyright (c) 2004, 2012 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/

package org.eclipse.freemarker.internal.core.documentModel.parser;

import java.io.CharArrayReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import org.eclipse.core.resources.IProject;
import org.eclipse.wst.sse.core.internal.ltk.parser.BlockMarker;
import org.eclipse.wst.sse.core.internal.ltk.parser.BlockTokenizer;
import org.eclipse.wst.sse.core.internal.provisional.text.ITextRegion;
import org.eclipse.wst.sse.core.internal.util.Debug;
import org.eclipse.wst.sse.core.utils.StringUtils;
import org.eclipse.wst.xml.core.internal.Logger;
import org.eclipse.wst.xml.core.internal.parser.IntStack;
import org.eclipse.wst.xml.core.internal.parser.regions.XMLParserRegionFactory;
import org.eclipse.wst.xml.core.internal.regions.DOMRegionContext;


/**
 * This class is a scanner generated by 
 * <a href="http://www.informatik.tu-muenchen.de/~kleing/jflex/">JFlex</a> 1.2.2
 * on 10/11/13 16:22 from the specification file
 * <tt>file:/D:/_Projects/Personal/Freemarker-DLTK2/org.eclipse.freemarker.core/devel/FMTokenizer.jflex</tt>
 */
public class FMTokenizer implements BlockTokenizer, DOMRegionContext, FMRegionContext {

  /** this character denotes the end of file */
  final public static int YYEOF = -1;

  /** lexical states */
  final public static int ST_XML_DOCTYPE_EXTERNAL_ID = 19;
  final public static int ST_XML_ELEMENT_DECLARATION_CONTENT = 23;
  final public static int ST_XML_PI_TAG_CLOSE = 11;
  final public static int ST_XML_DECLARATION_CLOSE = 17;
  final public static int ST_XML_PI_ATTRIBUTE_VALUE = 10;
  final public static int ST_FM_TAG_NAME = 27;
  final public static int ST_XML_TAG_NAME = 12;
  final public static int ST_XML_ATTRIBUTE_VALUE = 15;
  final public static int ST_XML_DOCTYPE_ID_SYSTEM = 21;
  final public static int ST_XML_ATTRIBUTE_NAME = 13;
  final public static int ST_XML_ELEMENT_DECLARATION = 22;
  final public static int ST_XML_DOCTYPE_DECLARATION = 18;
  final public static int ST_XML_ATTLIST_DECLARATION = 24;
  final public static int ST_XML_COMMENT_END = 4;
  final public static int ST_CDATA_TEXT = 1;
  final public static int ST_XML_COMMENT = 3;
  final public static int ST_PI_CONTENT = 7;
  final public static int ST_DIRECTIVE_END = 29;
  final public static int ST_PI_WS = 6;
  final public static int ST_CDATA_END = 2;
  final public static int ST_XML_ATTLIST_DECLARATION_CONTENT = 25;
  final public static int ST_BLOCK_TAG_SCAN = 26;
  final public static int ST_XML_PI_EQUALS = 9;
  final public static int ST_XML_DECLARATION = 16;
  final public static int YYINITIAL = 0;
  final public static int ST_DIRECTIVE_TEXT = 28;
  final public static int ST_XML_DOCTYPE_ID_PUBLIC = 20;
  final public static int ST_XML_EQUALS = 14;
  final public static int ST_PI = 5;
  final public static int ST_FM_BODY = 27;
  final public static int ST_XML_PI_ATTRIBUTE_NAME = 8;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\7\1\23\2\0\1\16\22\0\1\16\1\22\1\13\1\5"+
    "\1\6\1\20\1\14\1\15\1\6\1\6\1\6\1\6\1\6\1\11"+
    "\1\10\1\3\12\17\1\12\1\60\1\1\1\45\1\2\1\4\1\6"+
    "\1\35\1\61\1\33\1\34\1\50\1\56\1\37\1\37\1\42\1\37"+
    "\1\37\1\30\1\26\1\44\1\43\1\47\1\37\1\37\1\55\1\36"+
    "\1\57\2\37\1\24\1\46\1\37\1\32\1\0\1\21\1\0\1\12"+
    "\1\0\1\52\1\61\1\62\1\53\1\40\1\56\1\37\1\65\1\42"+
    "\2\37\1\31\1\27\1\44\1\43\1\47\1\37\1\37\1\41\1\51"+
    "\1\57\1\37\1\37\1\25\1\54\1\37\1\0\1\0\72\0\1\64"+
    "\10\0\27\63\1\0\37\63\1\0\72\63\2\0\13\63\2\0\10\63"+
    "\1\0\65\63\1\0\104\63\11\0\44\63\3\0\2\63\4\0\36\63"+
    "\70\0\131\63\22\0\7\63\16\0\2\64\56\0\106\64\32\0\2\64"+
    "\44\0\1\63\1\64\3\63\1\0\1\63\1\0\24\63\1\0\54\63"+
    "\1\0\7\63\3\0\1\63\1\0\1\63\1\0\1\63\1\0\1\63"+
    "\1\0\22\63\15\0\14\63\1\0\102\63\1\0\14\63\1\0\44\63"+
    "\1\0\4\64\11\0\65\63\2\0\2\63\2\0\2\63\3\0\34\63"+
    "\2\0\10\63\2\0\2\63\67\0\46\63\2\0\1\63\7\0\46\63"+
    "\12\0\21\64\1\0\27\64\1\0\3\64\1\0\1\64\1\0\2\64"+
    "\1\0\1\64\13\0\33\63\5\0\3\63\56\0\32\63\5\0\1\64"+
    "\12\63\10\64\15\0\12\64\6\0\1\64\107\63\2\0\5\63\1\0"+
    "\17\63\1\0\4\63\1\0\1\63\17\64\2\63\2\64\1\0\4\64"+
    "\2\0\12\64\u0207\0\3\64\1\0\65\63\2\0\1\64\1\63\20\64"+
    "\3\0\4\64\3\0\12\63\2\64\2\0\12\64\21\0\3\64\1\0"+
    "\10\63\2\0\2\63\2\0\26\63\1\0\7\63\1\0\1\63\3\0"+
    "\4\63\2\0\1\64\1\0\7\64\2\0\2\64\2\0\3\64\11\0"+
    "\1\64\4\0\2\63\1\0\3\63\2\64\2\0\12\64\2\63\20\0"+
    "\1\64\2\0\6\63\4\0\2\63\2\0\26\63\1\0\7\63\1\0"+
    "\2\63\1\0\2\63\1\0\2\63\2\0\1\64\1\0\5\64\4\0"+
    "\2\64\2\0\3\64\13\0\4\63\1\0\1\63\7\0\12\64\2\64"+
    "\3\63\14\0\3\64\1\0\7\63\1\0\1\63\1\0\3\63\1\0"+
    "\26\63\1\0\7\63\1\0\2\63\1\0\5\63\2\0\1\64\1\63"+
    "\10\64\1\0\3\64\1\0\3\64\22\0\1\63\5\0\12\64\21\0"+
    "\3\64\1\0\10\63\2\0\2\63\2\0\26\63\1\0\7\63\1\0"+
    "\2\63\2\0\4\63\2\0\1\64\1\63\6\64\3\0\2\64\2\0"+
    "\3\64\10\0\2\64\4\0\2\63\1\0\3\63\4\0\12\64\22\0"+
    "\2\64\1\0\6\63\3\0\3\63\1\0\4\63\3\0\2\63\1\0"+
    "\1\63\1\0\2\63\3\0\2\63\3\0\3\63\3\0\10\63\1\0"+
    "\3\63\4\0\5\64\3\0\3\64\1\0\4\64\11\0\1\64\17\0"+
    "\11\64\21\0\3\64\1\0\10\63\1\0\3\63\1\0\27\63\1\0"+
    "\12\63\1\0\5\63\4\0\7\64\1\0\3\64\1\0\4\64\7\0"+
    "\2\64\11\0\2\63\4\0\12\64\22\0\2\64\1\0\10\63\1\0"+
    "\3\63\1\0\27\63\1\0\12\63\1\0\5\63\4\0\7\64\1\0"+
    "\3\64\1\0\4\64\7\0\2\64\7\0\1\63\1\0\2\63\4\0"+
    "\12\64\22\0\2\64\1\0\10\63\1\0\3\63\1\0\27\63\1\0"+
    "\20\63\4\0\6\64\2\0\3\64\1\0\4\64\11\0\1\64\10\0"+
    "\2\63\4\0\12\64\221\0\56\63\1\0\1\63\1\64\2\63\7\64"+
    "\5\0\6\63\1\64\10\64\1\0\12\64\47\0\2\63\1\0\1\63"+
    "\2\0\2\63\1\0\1\63\2\0\1\63\6\0\4\63\1\0\7\63"+
    "\1\0\3\63\1\0\1\63\1\0\1\63\2\0\2\63\1\0\2\63"+
    "\1\0\1\63\1\64\2\63\6\64\1\0\2\64\1\63\2\0\5\63"+
    "\1\0\1\64\1\0\6\64\2\0\12\64\76\0\2\64\6\0\12\64"+
    "\13\0\1\64\1\0\1\64\1\0\1\64\4\0\2\64\10\63\1\0"+
    "\41\63\7\0\24\64\1\0\6\64\4\0\6\64\1\0\1\64\1\0"+
    "\25\64\3\0\7\64\1\0\1\64\346\0\46\63\12\0\47\63\11\0"+
    "\1\63\1\0\2\63\1\0\3\63\1\0\1\63\1\0\2\63\1\0"+
    "\5\63\51\0\1\63\1\0\1\63\1\0\1\63\13\0\1\63\1\0"+
    "\1\63\1\0\1\63\3\0\2\63\3\0\1\63\5\0\3\63\1\0"+
    "\1\63\1\0\1\63\1\0\1\63\1\0\1\63\3\0\2\63\3\0"+
    "\2\63\1\0\1\63\50\0\1\63\11\0\1\63\2\0\1\63\2\0"+
    "\2\63\7\0\2\63\1\0\1\63\1\0\7\63\50\0\1\63\4\0"+
    "\1\63\10\0\1\63\u0c06\0\234\63\4\0\132\63\6\0\26\63\2\0"+
    "\6\63\2\0\46\63\2\0\6\63\2\0\10\63\1\0\1\63\1\0"+
    "\1\63\1\0\1\63\1\0\37\63\2\0\65\63\1\0\7\63\1\0"+
    "\1\63\3\0\3\63\1\0\7\63\3\0\4\63\2\0\6\63\4\0"+
    "\15\63\5\0\3\63\1\0\7\63\323\0\15\64\4\0\1\64\104\0"+
    "\1\63\3\0\2\63\2\0\1\63\121\0\3\63\u0e82\0\1\64\1\0"+
    "\1\63\31\0\11\63\6\64\1\0\5\64\13\0\124\63\4\0\2\64"+
    "\2\0\2\64\2\0\132\63\1\0\3\64\6\0\50\63\u1cd3\0\u51a6\63"+
    "\u0c5a\0\u2ba4\63\134\0\u0800\0\u1ffe\0\2\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    54,   108,   162,   216,   270,   324,   378,   432,   486, 
      540,   594,   648,   702,   756,   810,   864,   918,   972,  1026, 
     1080,  1134,  1188,  1242,  1296,  1350,  1404,  1458,  1512,  1566, 
     1620,  1674,  1728,  1782,  1836,  1890,  1836,  1890,  1944,  1836, 
     1836,  1890,  1998,  2052,  2106,  2160,  2214,  2268,  2322,  1836, 
     1890,  2376,  2430,  2484,  1836,  2538,  2538,  2592,  2646,  2700, 
     2376,  2754,  2808,  1836,  2862,  2916,  2970,  3024,  1836,  3078, 
     3132,  3186,  3240,  3294,  1836,  3348,  3402,  3456,  3510,  3564, 
     3618,  3672,  3726,  3726,  3780,  3834,  3888,  3942,  3942,  3996, 
     4050,  4104,  4158,  4158,  4212,  4266,  4320,  4374,  1836,  4428, 
     4428,  4482,  4536,  4590,  4644,  1836,  1836,  1890,  1836,  1890, 
     1836,  1836,  1836,  4698,  4752,  4806,  4860,  4914,  4968,  5022, 
     5076,  5130,  5184,  1836,  5238,  5292,  1836,  1836,  2538,  5346, 
     2646,  1836,  5400,  2700,  1836,  3078,  5454,  3186,  1836,  5508, 
     3240,  4752,  5562,  5616,  5670,  3510,  1836,  5724,  5778,  3726, 
     5832,  3780,  1836,  5886,  5940,  5994,  5994,  6048,  6102,  3888, 
     3726,  3942,  6156,  3996,  1836,  6210,  4050,  4104,  3942,  4158, 
     6264,  4212,  1836,  6318,  6372,  6426,  6426,  6480,  6534,  6588, 
     6642,  4428,  6696,  4482,  1836,  6750,  6804,  6858,  6858,  6912, 
     6966,  7020,  7074,  7128,  7182,  7236,  7290,  7344,  7398,  7452, 
     1836,  1836,  1836,  1836,  2160,  7506,  7560,  7614,  7668,  7722, 
     7776,  5886,  7830,  7830,  6318,  7884,  7884,  7938,  7992,  6750, 
     8046,  8046,  8100,  8154,  1836,  8208,  1836,  8262,  8316,  8370, 
     8424,  8478,  8532,  8586,  8640,  8694,  6048,  6480,  8748,  6912, 
     8802,  8856,  8910,  1836,  8964,  9018,  9072,  9126,  9180,  9234, 
     9288,  9342,  9396,  9450,  9504,  9558,  9612,  1836,  1836,  9666, 
     9720,  9774,  9828,  1836,  1836,  1836,  9882,  9936,  9990, 10044, 
    10098, 10152,  1836, 10206,  4320,  4590, 10260, 10314, 10368, 10422, 
     2160
  };

  /** 
   * The packed transition table of the DFA
   */
  final private static String yy_packed = 
    "\1\37\1\40\12\37\1\41\3\37\1\42\45\37\1\43"+
    "\1\44\64\43\1\45\1\46\17\45\1\47\1\45\1\50"+
    "\42\45\1\51\1\52\64\51\1\45\1\46\7\45\1\53"+
    "\11\45\1\50\43\45\1\46\2\45\1\54\2\45\1\55"+
    "\2\45\1\56\3\45\1\55\4\45\1\55\1\57\1\60"+
    "\4\56\1\45\12\56\1\45\12\56\1\45\3\56\1\45"+
    "\1\56\1\45\1\46\2\45\1\54\2\45\1\61\6\45"+
    "\1\61\4\45\1\61\42\45\1\62\1\63\2\62\1\64"+
    "\16\62\1\50\42\62\1\45\1\46\2\45\1\65\2\45"+
    "\1\55\2\45\1\66\3\45\1\55\4\45\1\55\6\66"+
    "\1\45\12\66\1\45\12\66\1\45\3\66\1\45\1\66"+
    "\1\45\1\46\2\45\1\65\2\45\1\55\2\45\1\66"+
    "\3\45\1\55\4\45\1\55\6\66\1\45\12\66\1\67"+
    "\12\66\1\45\3\66\1\45\1\66\1\70\1\46\1\45"+
    "\1\71\1\72\2\70\1\55\3\70\1\73\1\70\1\74"+
    "\1\55\4\70\1\55\42\70\1\45\1\46\2\45\1\75"+
    "\16\45\1\50\42\45\1\76\1\77\1\100\1\101\6\76"+
    "\1\102\11\76\6\103\1\76\12\103\1\76\12\103\1\76"+
    "\3\103\1\76\1\103\1\45\1\77\1\100\1\101\3\45"+
    "\1\55\2\45\1\104\3\45\1\55\4\45\1\55\6\104"+
    "\1\45\12\104\1\45\12\104\1\45\3\104\1\45\1\104"+
    "\1\45\1\77\1\100\1\101\3\45\1\55\2\45\1\104"+
    "\3\45\1\55\4\45\1\55\6\104\1\45\12\104\1\105"+
    "\12\104\1\45\3\104\1\45\1\104\1\106\1\77\1\100"+
    "\1\107\3\106\1\55\3\106\1\110\1\106\1\111\1\55"+
    "\4\106\1\55\42\106\1\45\1\112\1\113\4\45\1\55"+
    "\6\45\1\55\4\45\1\55\10\45\1\114\1\115\2\45"+
    "\1\116\7\45\1\116\1\45\1\115\1\114\13\45\1\46"+
    "\1\113\4\45\1\55\6\45\1\55\4\45\1\55\6\45"+
    "\1\117\34\45\1\46\1\113\4\45\1\55\2\45\1\120"+
    "\3\45\1\55\4\45\1\55\6\120\1\117\12\120\1\45"+
    "\12\120\1\45\3\120\1\45\1\120\1\45\1\46\1\113"+
    "\4\45\1\55\6\45\1\55\4\45\1\55\6\45\1\117"+
    "\6\45\1\121\5\45\1\122\5\45\1\121\10\45\1\123"+
    "\1\46\1\113\1\124\3\123\1\55\3\123\1\125\1\123"+
    "\1\126\1\55\4\123\1\55\6\123\1\127\33\123\1\130"+
    "\1\46\1\113\1\131\3\130\1\55\3\130\1\132\1\130"+
    "\1\133\1\55\4\130\1\55\6\130\1\134\33\130\1\135"+
    "\1\46\1\113\1\136\3\135\1\55\3\135\1\137\1\135"+
    "\1\140\1\55\4\135\1\55\42\135\1\141\1\142\1\143"+
    "\63\141\1\144\1\46\1\113\1\145\3\144\1\55\3\144"+
    "\1\146\1\144\1\147\1\55\4\144\1\55\42\144\1\150"+
    "\1\151\1\152\63\150\1\153\1\154\64\153\1\45\1\46"+
    "\21\45\1\50\42\45\1\155\1\156\64\155\1\45\1\46"+
    "\1\157\20\45\1\50\42\45\1\37\1\0\12\37\1\0"+
    "\3\37\1\0\45\37\3\0\1\160\1\161\1\162\14\0"+
    "\1\163\50\0\1\164\1\0\1\165\2\0\1\166\3\0"+
    "\1\165\4\0\1\165\6\166\1\0\12\166\1\0\12\166"+
    "\1\0\3\166\1\0\1\166\7\0\1\165\2\0\1\167"+
    "\3\0\1\165\1\0\1\170\2\0\1\165\6\167\1\0"+
    "\12\167\1\0\12\167\1\0\3\167\1\0\1\167\73\0"+
    "\1\162\14\0\1\171\64\0\1\172\55\0\1\173\56\0"+
    "\1\174\72\0\1\55\6\0\1\55\4\0\1\55\52\0"+
    "\3\56\4\0\1\56\4\0\6\56\1\0\12\56\1\0"+
    "\12\56\1\0\5\56\10\0\3\56\4\0\1\56\4\0"+
    "\2\56\2\175\2\56\1\0\12\56\1\0\12\56\1\0"+
    "\5\56\10\0\3\56\4\0\1\56\4\0\2\56\1\175"+
    "\1\176\2\56\1\0\12\56\1\0\12\56\1\0\5\56"+
    "\7\0\1\61\6\0\1\61\4\0\1\61\44\0\1\177"+
    "\65\0\1\200\73\0\3\66\4\0\1\66\4\0\6\66"+
    "\1\0\12\66\1\0\12\66\1\0\5\66\1\70\2\0"+
    "\1\201\3\70\1\0\3\70\1\0\1\70\2\0\4\70"+
    "\1\0\43\70\1\0\1\200\1\201\3\70\1\0\3\70"+
    "\1\0\1\70\2\0\4\70\1\0\42\70\1\73\2\202"+
    "\1\203\3\73\1\202\3\73\1\204\1\73\2\202\4\73"+
    "\1\202\42\73\1\74\2\205\1\206\3\74\1\205\3\74"+
    "\1\205\1\74\1\204\1\205\4\74\1\205\42\74\1\76"+
    "\3\0\20\76\6\0\1\76\12\0\1\76\12\0\1\76"+
    "\3\0\1\76\4\0\1\160\1\0\1\162\14\0\1\163"+
    "\45\0\1\207\63\0\1\76\3\0\4\76\3\102\4\76"+
    "\1\102\4\76\6\103\1\76\12\103\1\76\12\103\1\76"+
    "\3\103\1\102\1\103\10\0\3\103\4\0\1\103\4\0"+
    "\6\103\1\0\12\103\1\0\12\103\1\0\5\103\10\0"+
    "\3\104\4\0\1\104\4\0\6\104\1\0\12\104\1\0"+
    "\12\104\1\0\5\104\1\106\2\0\1\210\3\106\1\0"+
    "\3\106\1\0\1\106\2\0\4\106\1\0\43\106\1\0"+
    "\1\207\1\210\3\106\1\0\3\106\1\0\1\106\2\0"+
    "\4\106\1\0\42\106\1\110\2\211\1\212\3\110\1\211"+
    "\3\110\1\213\1\110\2\211\4\110\1\211\42\110\1\111"+
    "\2\214\1\215\3\111\1\214\3\111\1\214\1\111\1\213"+
    "\1\214\4\111\1\214\42\111\3\0\1\160\1\0\1\162"+
    "\14\0\1\216\106\0\1\217\60\0\1\220\12\0\1\220"+
    "\44\0\2\221\34\0\21\222\1\223\44\222\10\0\3\120"+
    "\4\0\1\120\4\0\6\120\1\0\12\120\1\0\12\120"+
    "\1\0\5\120\46\0\1\224\5\0\1\224\70\0\1\225"+
    "\6\0\1\123\2\0\1\226\3\123\1\0\3\123\1\0"+
    "\1\123\2\0\4\123\1\0\42\123\1\125\2\227\1\230"+
    "\3\125\1\227\3\125\1\231\1\125\2\227\4\125\1\227"+
    "\42\125\1\232\2\233\1\234\3\235\1\233\3\235\1\233"+
    "\1\232\1\236\1\237\2\235\1\232\1\235\1\237\6\235"+
    "\1\232\30\235\2\232\1\235\1\127\2\222\1\240\3\127"+
    "\1\222\3\127\1\222\1\127\2\222\2\127\1\241\1\127"+
    "\1\222\42\127\1\130\2\0\1\242\3\130\1\0\3\130"+
    "\1\0\1\130\2\0\4\130\1\0\42\130\1\132\2\243"+
    "\1\244\3\132\1\243\3\132\1\245\1\132\2\243\4\132"+
    "\1\243\42\132\1\133\2\246\1\247\3\133\1\246\3\133"+
    "\1\246\1\133\1\245\1\246\4\133\1\246\42\133\1\134"+
    "\2\222\1\250\3\134\1\222\3\134\1\222\1\134\2\222"+
    "\2\134\1\251\1\134\1\222\42\134\1\135\2\0\1\252"+
    "\3\135\1\0\3\135\1\0\1\135\2\0\4\135\1\0"+
    "\42\135\1\137\2\253\1\254\3\137\1\253\3\137\1\255"+
    "\1\137\2\253\4\137\1\253\42\137\1\256\2\257\1\260"+
    "\3\261\1\257\3\261\1\257\1\256\1\262\1\263\2\261"+
    "\1\256\1\261\1\263\6\261\1\256\30\261\2\256\1\261"+
    "\2\141\1\0\65\141\1\0\2\141\1\264\14\141\1\265"+
    "\43\141\1\144\2\0\1\266\3\144\1\0\3\144\1\0"+
    "\1\144\2\0\4\144\1\0\42\144\1\146\2\267\1\270"+
    "\3\146\1\267\3\146\1\271\1\146\2\267\4\146\1\267"+
    "\42\146\1\272\2\273\1\274\3\275\1\273\3\275\1\273"+
    "\1\272\1\276\1\277\2\275\1\272\1\275\1\277\6\275"+
    "\1\272\30\275\2\272\1\275\2\150\1\0\65\150\1\0"+
    "\2\150\1\300\14\150\1\301\43\150\12\0\1\302\11\0"+
    "\6\302\1\0\12\302\1\0\12\302\1\0\3\302\1\0"+
    "\1\302\11\0\1\303\20\0\1\304\52\0\1\305\5\0"+
    "\1\306\47\0\1\165\2\0\1\37\3\0\1\165\4\0"+
    "\1\165\6\37\1\0\12\37\1\0\12\37\1\0\3\37"+
    "\1\0\1\37\1\307\1\0\5\307\1\310\3\166\1\307"+
    "\1\0\1\307\1\310\1\166\1\0\2\307\1\310\6\166"+
    "\1\307\12\166\1\307\12\166\1\311\5\166\1\307\1\0"+
    "\5\307\1\310\3\167\1\307\1\0\1\307\1\310\1\167"+
    "\1\0\2\307\1\310\6\167\1\307\12\167\1\307\12\167"+
    "\1\312\5\167\20\0\1\170\77\0\1\304\35\0\1\313"+
    "\65\0\1\314\73\0\3\56\4\0\1\56\4\0\4\56"+
    "\2\315\1\0\12\56\1\0\12\56\1\0\5\56\10\0"+
    "\3\56\4\0\1\56\4\0\4\56\1\315\1\316\1\0"+
    "\12\56\1\0\12\56\1\0\5\56\13\202\1\204\52\202"+
    "\15\205\1\204\50\205\13\211\1\213\52\211\15\214\1\213"+
    "\50\214\33\0\1\317\26\0\1\317\41\0\1\320\12\0"+
    "\1\320\54\0\1\321\7\0\1\321\56\0\1\322\13\0"+
    "\1\322\71\0\1\323\4\0\13\227\1\231\52\227\1\232"+
    "\2\233\1\324\3\232\1\233\3\232\1\233\1\232\1\231"+
    "\1\233\4\232\1\233\42\232\15\233\1\231\50\233\1\232"+
    "\2\233\1\324\3\232\1\233\3\232\1\233\1\232\1\325"+
    "\1\233\4\232\1\233\42\232\15\0\1\326\50\0\15\233"+
    "\1\325\50\233\13\243\1\245\52\243\15\246\1\245\50\246"+
    "\13\253\1\255\52\253\1\256\2\257\1\327\3\256\1\257"+
    "\3\256\1\257\1\256\1\255\1\257\4\256\1\257\42\256"+
    "\15\257\1\255\50\257\1\256\2\257\1\327\3\256\1\257"+
    "\3\256\1\257\1\256\1\330\1\257\4\256\1\257\42\256"+
    "\15\0\1\331\50\0\15\257\1\330\50\257\2\141\1\0"+
    "\7\141\1\332\11\141\6\332\1\141\12\332\1\141\12\332"+
    "\1\141\3\332\1\141\1\332\2\141\1\0\27\141\1\333"+
    "\33\141\13\267\1\271\52\267\1\272\2\273\1\334\3\272"+
    "\1\273\3\272\1\273\1\272\1\271\1\273\4\272\1\273"+
    "\42\272\15\273\1\271\50\273\1\272\2\273\1\334\3\272"+
    "\1\273\3\272\1\273\1\272\1\335\1\273\4\272\1\273"+
    "\42\272\15\0\1\336\50\0\15\273\1\335\50\273\2\150"+
    "\1\0\7\150\1\337\11\150\6\337\1\150\12\337\1\150"+
    "\12\337\1\150\3\337\1\150\1\337\2\150\1\0\27\150"+
    "\1\340\33\150\10\0\3\302\4\0\1\302\4\0\6\302"+
    "\1\0\12\302\1\0\12\302\1\0\5\302\11\0\1\341"+
    "\107\0\1\342\51\0\1\305\40\0\1\343\24\0\1\344"+
    "\13\0\3\344\2\0\1\344\7\0\1\344\1\0\2\344"+
    "\2\0\1\344\2\0\2\344\3\0\1\307\1\0\12\307"+
    "\1\0\3\307\1\0\37\307\1\0\6\307\1\0\5\307"+
    "\1\310\2\307\1\345\1\307\1\0\1\307\1\310\1\307"+
    "\1\0\2\307\1\310\6\345\1\307\12\345\1\307\12\345"+
    "\1\346\3\345\1\307\1\345\10\0\1\56\1\347\1\56"+
    "\4\0\1\56\4\0\6\56\1\0\12\56\1\0\12\56"+
    "\1\0\5\56\36\0\1\350\12\0\1\350\44\0\2\351"+
    "\62\0\2\352\74\0\1\353\12\0\1\353\44\0\2\354"+
    "\37\0\4\355\1\0\3\355\2\0\1\236\3\355\1\0"+
    "\10\355\1\0\30\355\2\0\1\355\3\0\4\356\1\0"+
    "\3\356\2\0\1\262\3\356\1\0\10\356\1\0\30\356"+
    "\2\0\1\356\2\141\1\0\5\141\3\332\4\141\1\332"+
    "\4\141\6\332\1\141\12\332\1\141\12\332\1\141\5\332"+
    "\2\141\1\0\30\141\1\357\32\141\3\0\4\360\1\0"+
    "\3\360\2\0\1\276\3\360\1\0\10\360\1\0\30\360"+
    "\2\0\1\360\2\150\1\0\5\150\3\337\4\150\1\337"+
    "\4\150\6\337\1\150\12\337\1\150\12\337\1\150\5\337"+
    "\2\150\1\0\30\150\1\361\32\150\34\0\1\362\50\0"+
    "\1\344\13\0\3\344\2\0\1\344\7\0\1\344\1\0"+
    "\2\344\2\0\1\344\1\0\1\343\2\344\3\0\1\307"+
    "\1\0\5\307\1\363\3\345\1\307\1\0\1\307\1\363"+
    "\1\345\1\0\2\307\1\363\6\345\1\307\12\345\1\307"+
    "\12\345\1\364\5\345\60\0\1\346\15\0\3\56\4\0"+
    "\1\56\4\0\6\56\1\0\6\56\1\365\3\56\1\0"+
    "\12\56\1\0\5\56\46\0\1\366\5\0\1\366\53\0"+
    "\1\367\63\0\1\370\7\0\1\370\55\0\1\371\7\0"+
    "\1\371\57\0\1\372\23\0\2\141\1\0\31\141\1\373"+
    "\31\141\2\150\1\0\31\150\1\374\31\150\35\0\1\375"+
    "\30\0\1\307\1\0\5\307\1\363\2\307\1\345\1\307"+
    "\1\0\1\307\1\363\1\307\1\0\2\307\1\363\6\345"+
    "\1\307\12\345\1\307\12\345\1\0\3\345\1\307\1\345"+
    "\10\0\3\56\4\0\1\56\4\0\6\56\1\0\12\56"+
    "\1\0\3\56\1\376\6\56\1\0\5\56\47\0\1\377"+
    "\57\0\1\u0100\13\0\1\u0100\54\0\1\u0101\47\0\2\u0102"+
    "\71\0\1\u0103\26\0\1\u0103\3\0\2\141\1\0\32\141"+
    "\1\u0104\30\141\2\150\1\0\32\150\1\u0105\30\150\36\0"+
    "\1\u0106\37\0\3\56\4\0\1\56\4\0\6\56\1\0"+
    "\12\56\1\0\6\56\1\u0107\3\56\1\0\5\56\40\0"+
    "\1\u0108\7\0\1\u0108\53\0\1\u0109\12\0\1\u0109\52\0"+
    "\1\u010a\12\0\1\u010a\14\0\2\141\1\0\33\141\1\u010b"+
    "\27\141\2\150\1\0\33\150\1\u010c\27\150\35\0\1\u010d"+
    "\40\0\3\56\4\0\1\56\4\0\5\56\1\u010e\1\0"+
    "\12\56\1\0\12\56\1\0\5\56\2\141\1\0\32\141"+
    "\1\u010f\30\141\2\150\1\0\32\150\1\u0110\30\150\32\0"+
    "\1\u0111\43\0\3\56\4\0\1\56\4\0\6\56\1\0"+
    "\5\56\1\u0112\4\56\1\0\12\56\1\0\5\56\2\141"+
    "\1\0\27\141\1\u0113\33\141\2\150\1\0\27\150\1\u0114"+
    "\33\150\10\0\3\56\4\0\1\56\4\0\6\56\1\0"+
    "\6\56\1\u0115\3\56\1\0\12\56\1\0\5\56\10\0"+
    "\3\56\4\0\1\56\4\0\6\56\1\0\12\56\1\0"+
    "\12\56\1\0\4\56\1\u0116\10\0\3\56\4\0\1\56"+
    "\4\0\6\56\1\0\5\56\1\u0117\4\56\1\0\12\56"+
    "\1\0\5\56\10\0\3\56\4\0\1\56\4\0\6\56"+
    "\1\0\5\56\1\u0118\4\56\1\0\12\56\1\0\5\56"+
    "\10\0\3\56\4\0\1\56\4\0\6\56\1\0\12\56"+
    "\1\0\3\56\1\u0119\6\56\1\0\5\56";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack(yy_packed);


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  // final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",		//$NON-NLS-1$
    "Internal error: unknown state",		//$NON-NLS-1$
    "Error: could not match input",		//$NON-NLS-1$
    "Error: pushback value was too large"	//$NON-NLS-1$
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     1,  0,  0,  0,  0,  1,  0,  0,  1,  1,  1,  0,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  0,  1,  1, 
     1,  1,  9,  1,  9,  1,  1,  9,  9,  1,  1,  1,  1,  1,  1,  1, 
     1,  9,  1,  1,  1,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  9, 
     1,  1,  1,  1,  9,  1,  1,  1,  1,  1,  9,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  9,  1,  1,  1,  1,  1,  1,  9,  9,  1,  9,  1,  9,  9, 
     9,  0,  1,  0,  0,  1,  1,  1,  0,  0,  0,  9,  1,  1,  9,  9, 
     0,  0,  0,  9,  0,  0,  9,  0,  0,  0,  9,  0,  0,  0,  0,  0, 
     0,  0,  9,  0,  0,  0,  0,  0,  9,  1,  0,  0,  1,  1,  0,  0, 
     1,  0,  0,  0,  9,  0,  0,  0,  1,  0,  0,  0,  9,  1,  0,  0, 
     1,  1,  0,  1,  1,  0,  0,  0,  9,  1,  0,  0,  1,  1,  0,  1, 
     1,  1,  0,  0,  0,  0,  1,  1,  9,  9,  9,  9,  1,  1,  0,  0, 
     0,  0,  0,  0,  1,  0,  0,  1,  0,  1,  1,  0,  1,  0,  1,  1, 
     9,  0,  9,  0,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  1,  0, 
     1,  0,  1,  9,  1,  0,  0,  0,  0,  0,  1,  1,  0,  1,  0,  0, 
     0,  9,  9,  1,  1,  0,  1,  9,  9,  9,  1,  1,  0,  1,  1,  1, 
     9,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[16384];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  // private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  // private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  // private boolean yy_atBOL;

  /** yy_atEOF == true <=> the scanner has returned a value for EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	private int fTokenCount = 0;
 
	// required holders for white-space compacting
	private boolean fShouldLoadBuffered = false;
	private String fBufferedContext = null;
	private int fBufferedStart = 1;
	private int fBufferedLength = 0;
	private String f_context = null;

	// state stack for handling embedded regions
	private IntStack fStateStack = new IntStack();

	private String context = null;
	private int start = 0;
	private int textLength = 0;
	private int length = 0;

	// offset for tracking position specific block tags
	private int fOffset = 0;
	
	// the name of the current tag being opened
	private String fCurrentTagName = null;

	// the list of tag name BlockMarkers
	private List fBlockMarkers = new ArrayList();

	// required to not seek text blocks on an end tag
	private boolean fIsBlockingEnabled = false;
	private boolean fIsCaseSensitiveBlocking = true;

	private XMLParserRegionFactory fRegionFactory = new XMLParserRegionFactory();
/**
 * user method 
 */
public final void addBlockMarker(BlockMarker marker) {
	if(containsTagName(marker.getTagName()))
		return;
	fBlockMarkers.add(marker);
}
/**
 * user method 
 */
public final void removeBlockMarker(BlockMarker marker) {
	fBlockMarkers.remove(marker);
}
/**
 * user method 
 */
public final void removeBlockMarker(String tagname) {
	if (fBlockMarkers != null) {
		Iterator blocks = fBlockMarkers.iterator();
		while (blocks.hasNext()) {
			if (((BlockMarker) blocks.next()).getTagName().equals(tagname))
				blocks.remove();
		}
	}
}
/* user method */
public final boolean isCaseSensitiveBlocking() {
	return fIsCaseSensitiveBlocking;
}
/* user method */
public final void setCaseSensitiveBlocking(boolean newValue) {
	fIsCaseSensitiveBlocking = newValue;
}
/* user method */
public boolean getBlockMarkerCaseSensitivity() {
        return getBlockMarkerCaseSensitivity(fCurrentTagName);
}
/* user method */
public boolean getBlockMarkerCaseSensitivity(String name) {
	Iterator iterator = fBlockMarkers.iterator();
	while(iterator.hasNext()) {
		BlockMarker marker = (BlockMarker)iterator.next();
		boolean casesensitive = marker.isCaseSensitive();
		if(casesensitive && marker.getTagName().equals(name))
			return casesensitive;
		else if(!casesensitive && marker.getTagName().equalsIgnoreCase(name))
			return casesensitive;
	}
	return true;
}
/* user method */
public String getBlockMarkerContext() {
	return getBlockMarkerContext(fCurrentTagName);
}
/* user method */
public String getBlockMarkerContext(String name) {
	Iterator iterator = fBlockMarkers.iterator();
	while(iterator.hasNext()) {
		BlockMarker marker = (BlockMarker)iterator.next();
		if(marker.getTagName().equals(name))
			return marker.getContext();
	}
	return BLOCK_TEXT;
}
/* user method */
public List getBlockMarkers() {
	return fBlockMarkers;
}
/* user method */
public final int getOffset() {
	return fOffset + yychar;
}
private final boolean isBlockMarker() {
	return isBlockMarker(fCurrentTagName);
}
private final boolean isBlockMarker(String tagName) {
	if (!fIsBlockingEnabled)
		return false;
	return containsTagName(tagName);
}
/**
 * user method
 */
public final void beginBlockTagScan(String newTagName) {
	beginBlockMarkerScan(newTagName, BLOCK_TEXT);
}
/**
 * user method
 *
 * Special tokenizer setup.  Allows tokenization to be initiated at the
 * start of a text block within a "newTagName" tag.
 *
 * Example: 
 *	Tokenizer toker = new Tokenizer();
 *	toker.setCaseSensitiveBlocking(false);
 *	toker.reset(new java.io.StringReader("afiuhqwkejhtasihgalkwhtq</scripter></scr></script>asgdasga"));
 *	toker.beginBlockMarkerScan("script", BLOCK_TEXT);
 *	toker.getRegions(); 
 *
 * Returns:
 *	BLOCK_TEXT: 0-40
 *	XML_END_TAG_OPEN: 41-42
 *	XML_TAG_NAME: 43-48
 *	XML_TAG_CLOSE: 49-49
 *	XML_CONTENT: 50-57
 *
 */
public final void beginBlockMarkerScan(String newTagName, String blockcontext) {
	yybegin(ST_BLOCK_TAG_SCAN);
	fCurrentTagName = newTagName;
}
/**
 * Method doScan.
 * 
 * Returns a context region for all of the text from the current position upto the end of input or
 * to right *before* the first occurence of searchString
 * 
 * @param searchString - target string to search for ex.: "-->", "</tagname"
 * @param requireTailSeparator - whether the target must be immediately followed by whitespace or '>'
 * @param context - the context of the scanned region if non-zero length
 * @param exitState - the state to go to if the region was of non-zero length
 * @param abortState - the state to go to if the searchString was found immediately
 * @return String - the context found: the desired context on a non-zero length match, the abortContext on immediate success
 * @throws IOException
 */
private final String doScan(String searchString, boolean requireTailSeparator, String searchContext, int exitState, int immediateFallbackState) throws IOException {
	boolean stillSearching = true;
	// Disable further block (probably)
	fIsBlockingEnabled = false;
	int searchStringLength = searchString.length();
	int n = 0;
	char lastCheckChar;
	int i;
	boolean same = false;
	while (stillSearching) {
		n = 0;
		// Ensure that enough data from the input exists to compare against the search String.
		n = yy_advance();
		while(n != YYEOF && yy_currentPos < searchStringLength)
			n = yy_advance();
		// If the input was too short or we've exhausted the input, stop immediately.
		if (n == YYEOF) {
			stillSearching = false;
		}
		else {
			same = true;
			// Ensure that we've not encountered a complete block (<%%>) that was *shorter* than the closeTagString and
			// thus found twice at current-targetLength [since the first scan would have come out this far anyway].
			// Check the characters in the target versus the last targetLength characters read from the buffer
			// and see if it matches
			
			// safety check for array accesses (yy_currentPos is the *last* character we can check against)
			if(yy_currentPos >= searchStringLength && yy_currentPos <= yy_buffer.length) {
				for(i = 0; i < searchStringLength; i++) {
					if(same && fIsCaseSensitiveBlocking)
						same = yy_buffer[i + yy_currentPos - searchStringLength] == searchString.charAt(i);
					else if(same && !fIsCaseSensitiveBlocking)
						same = Character.toLowerCase(yy_buffer[i + yy_currentPos - searchStringLength]) == Character.toLowerCase(searchString.charAt(i));
				}
			}
			// safety check failed; no match is possible right now
			else {
				same = false;
			}
			if (same && requireTailSeparator && yy_currentPos < yy_buffer.length) {
				// Additional check for close tags to ensure that targetString="</script" doesn't match
				// "</scriptS"
				lastCheckChar = yy_buffer[yy_currentPos];
				// Succeed on "</script>" and "</script "
				if(lastCheckChar == '>' || Character.isWhitespace(lastCheckChar))
					stillSearching = false;
			}
			else {
				stillSearching = !same || (yy_currentPos < yy_startRead + searchStringLength);
			}
		}
	}
	if (n != YYEOF || same) {
		// We've stopped short of the end or definitely found a match
		yy_markedPos = yy_currentPos - searchStringLength;
		yy_currentPos = yy_markedPos + 1;
		// If the searchString occurs at the very beginning of what would have
		// been a Block, resume scanning normally immediately
		if (yy_markedPos == yy_startRead) {
			yybegin(immediateFallbackState);
			return primGetNextToken();
		}
	}
	else {
		// We ran through the rest of the input
		yy_markedPos = yy_currentPos;
		yy_currentPos++;
	}
	yybegin(exitState);
	// If the ending occurs at the very beginning of what would have
	// been a Block, resume scanning normally immediately
	if(yy_markedPos == yy_startRead)
		return primGetNextToken();
	return searchContext;
}
/**
 * user method
 *
 * A generic lookahead-like operation
 */
private final String doBlockScan(String target, String targetContext, int immediateFallbackState) throws IOException {
	return doScan(target, false, targetContext, immediateFallbackState, immediateFallbackState);
}
/**
 * user method 
 * does a lookahead for the current tag name
 */
private final String doBlockTagScan() throws IOException {
        fIsCaseSensitiveBlocking = getBlockMarkerCaseSensitivity();
	return doScan("</" + fCurrentTagName, true, getBlockMarkerContext(fCurrentTagName), YYINITIAL, YYINITIAL);
}

private IProject project;

public void setProject(IProject project) {
	this.project = project;
}

/**
 * user method
 *
 * Converts the raw context String returned by the primGetNextToken()
 * method into a full ITextRegion by pulling in values for the
 * current offset within the scanning text.
 *
 * Returns null when EOF is encountered and attaches intermittently
 * discovered whitespace onto the end of useful regions.
 *
 * Note that this algorithm caches the token following the one being returned
 * so that whitespace can be collapsed.
 */
public final ITextRegion getNextToken() throws IOException {
	// load the starting non-whitespace token (assume that it is so)
	if (fShouldLoadBuffered) {
		context = fBufferedContext;
		start = fBufferedStart;
		textLength = length = fBufferedLength;
		fShouldLoadBuffered = false;
	}
	else {
		context = primGetNextToken();
		if (context == XML_TAG_NAME) {
			if(containsTagName(yy_buffer, yy_startRead, yy_markedPos-yy_startRead))
				fCurrentTagName = yytext();
			else
				fCurrentTagName = null;
		}
		else if (context == XML_TAG_OPEN) {
			fIsBlockingEnabled = true;
		}
		else if (context == XML_END_TAG_OPEN) {
			fIsBlockingEnabled = false;
		}
		start = yychar;
		textLength = length = yylength();
		if (yy_atEOF) {
			fTokenCount++;
			return null;
		}
	}
	// store the next token
	f_context = primGetNextToken();
	if (f_context == XML_TAG_NAME) {
		if(containsTagName(yy_buffer, yy_startRead, yy_markedPos-yy_startRead))
			fCurrentTagName = yytext();
		else
			fCurrentTagName = null;
	}
	else if (f_context == XML_TAG_OPEN) {
		fIsBlockingEnabled = true;
	}
	else if (f_context == XML_END_TAG_OPEN) {
		fIsBlockingEnabled = false;
	}
	fBufferedContext = f_context;
	fBufferedStart = yychar;
	fBufferedLength = yylength();
	fShouldLoadBuffered = true;
	if (fBufferedContext == WHITE_SPACE) {
		fShouldLoadBuffered = false;
		length += fBufferedLength;
	}
	if (context == null) {
		// EOF
		if (Debug.debugTokenizer) {
			System.out.println(getClass().getName() + " discovered " + fTokenCount + " tokens."); //$NON-NLS-2$//$NON-NLS-1$
		}
		return null;
	}
	fTokenCount++;
	return fRegionFactory.createToken(context, start, textLength, length, null, fCurrentTagName);
}
/* user method */
public FMTokenizer(){
	super();
}
/* user method */
public FMTokenizer(char[] charArray){
		this(new CharArrayReader(charArray));
}
/* user method */
public void reset(char[] charArray) {
	reset(new CharArrayReader(charArray), 0);
}
/* user method */
public void reset(char[] charArray, int newOffset) {
	reset(new CharArrayReader(charArray), newOffset);
}
/* user method */
public void reset(java.io.InputStream in) {
	reset(new java.io.InputStreamReader(in), 0);
}
/* user method */
public void reset(java.io.InputStream in, int newOffset) {
	reset(new java.io.InputStreamReader(in), newOffset);
}
/* user method */
public void reset(java.io.Reader in) {
	reset(in, 0);
}
/**
 * user method *
 *
 * Reset internal counters and vars to "newly created" values, in the hopes
 * that resetting a pre-existing tokenizer is faster than creating a new one.
 *
 * This method contains code blocks that were essentially duplicated from the
 * <em>generated</em> output of this specification before this method was
 * added.  Those code blocks were under the above copyright.
 */
public void reset(java.io.Reader in, int newOffset) {
	if (Debug.debugTokenizer) {
		System.out.println("resetting tokenizer");//$NON-NLS-1$
	}
	fOffset = newOffset;

	/* the input device */
	yy_reader = in;

	/* the current state of the DFA */
	yy_state = 0;

	/* the current lexical state */
	yy_lexical_state = YYINITIAL;

	/* this buffer contains the current text to be matched and is
	the source of the yytext() string */
	java.util.Arrays.fill(yy_buffer, (char)0);

	/* the textposition at the last accepting state */
	yy_markedPos = 0;

	/* the textposition at the last state to be included in yytext */
	//yy_pushbackPos = 0;

	/* the current text position in the buffer */
	yy_currentPos = 0;

	/* startRead marks the beginning of the yytext() string in the buffer */
	yy_startRead = 0;

	/** 
	 * endRead marks the last character in the buffer, that has been read
	 * from input 
	 */
	yy_endRead = 0;

	/* number of newlines encountered up to the start of the matched text */
	//yyline = 0;

	/* the number of characters up to the start of the matched text */
	yychar = 0;

	/* yy_atEOF == true <=> the scanner has returned a value for EOF */
	yy_atEOF = false;

	/* denotes if the user-EOF-code has already been executed */
	yy_eof_done = false;


	/* user vars: */
	fTokenCount = 0;
 
	fShouldLoadBuffered = false;
	fBufferedContext = null;
	fBufferedStart = 1;
	fBufferedLength = 0;
	fStateStack = new IntStack();

	context = null;
	start = 0;
	textLength = 0;
	length = 0;
}

	/**
	 * user method
	 *
	 */
	public BlockTokenizer newInstance() {
		FMTokenizer newInstance = new FMTokenizer();
		// global tagmarkers can be shared; they have no state and 
		// are never destroyed (e.g. 'release')
		for(int i = 0; i < fBlockMarkers.size(); i++) {
			BlockMarker blockMarker = (BlockMarker) fBlockMarkers.get(i);
			if(blockMarker.isGlobal())
				newInstance.addBlockMarker(blockMarker);
		}
		return newInstance;
	}
/* user method */
private final String scanXMLCommentText() throws IOException {
	// Scan for '-->' and return the text up to that point as
	//   XML_COMMENT_TEXT unless the string occurs IMMEDIATELY, in which
	//  case change to the ST_XML_COMMENT_END state and return the next
	//  context as usual.
	return doScan("-->", false, XML_COMMENT_TEXT, ST_XML_COMMENT_END, ST_XML_COMMENT_END);
}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public FMTokenizer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public FMTokenizer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the unpacked transition table
   */
  private static int [] yy_unpack(String packed) {
    int [] trans = new int[10476];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 3340) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return trans;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1372) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Gets the next input character.
   *
   * @return      the next character of the input stream, EOF if the
   *              end of the stream is reached.
   * @exception   IOException  if any I/O-Error occurs
   */
  private int yy_advance() throws java.io.IOException {

    /* standard case */
    if (yy_currentPos < yy_endRead) return yy_buffer[yy_currentPos++];

    /* if the eof is reached, we don't need to work hard */ 
    if (yy_atEOF) return YYEOF;

    /* otherwise: need to refill the buffer */

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if ( numRead == -1 ) return YYEOF;

    yy_endRead+= numRead;

    return yy_buffer[yy_currentPos++];
  }

    
  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */
    yy_reader.close();
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }

  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }

  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning - from the SED JFlex skeleton
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    try {
      Logger.log(Logger.ERROR, YY_ERROR_MSG[errorCode]);
    }
    catch (ArrayIndexOutOfBoundsException e) {
      Logger.log(Logger.ERROR, YY_ERROR_MSG[YY_UNKNOWN_ERROR]);
    }
    // DO NOT EXIT the VM on an error
    // System.exit(1);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  void yypushback(int number) {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }

	/**
	 * user method - skeleton.sed
	 */
	protected final boolean containsTagName(char[] markerTagName, int offset, int tagnameLength) {
		for(int j = 0; j < fBlockMarkers.size(); j++) {
			BlockMarker marker = (BlockMarker)fBlockMarkers.get(j);
			if(marker.getTagName().length() == tagnameLength) {
				boolean matchesSoFar = true;
				for(int i = 0; i < tagnameLength && matchesSoFar; i++) {
					if(marker.isCaseSensitive()) {
						if(marker.getTagName().charAt(i) != markerTagName[i + offset])
							matchesSoFar = false;
					}
					else {
						if(Character.toLowerCase(marker.getTagName().charAt(i)) != Character.toLowerCase(markerTagName[i + offset]))
							matchesSoFar = false;
					}
				}
				if(matchesSoFar)
					return true;
			}
		}
		return false;
	}

	/**
	 * user method - skeleton.sed
	 *
	 * Return ALL of the regions scannable within the remaining text
	 * Note: for verification use
	 */
	public final List getRegions() {
		List tokens = new ArrayList();
		ITextRegion region = null;
		try {
			region = getNextToken();
			while(region != null) {
				if (region != null) {
					tokens.add(region);
				}
				region = getNextToken();
			}
		}
		catch (StackOverflowError e) {
			Logger.logException(getClass().getName()+": input could not be tokenized correctly at position " + getOffset(), e);//$NON-NLS-1$
			throw e;
		}
		catch (Exception e) {
			// Since this is convenience method and NOT the recommended 
			// way of getting tokens, many errors are simply hidden
			Logger.logException("Exception not handled retrieving regions: " + e.getLocalizedMessage(), e);//$NON-NLS-1$
		}
		return tokens;
	}
	/**
	 * user method - skeleton.sed
	 */
	private final void dump(String s) {
		if (Debug.debugTokenizer) {
			System.out.println(s + " (" + yychar + "-" + //$NON-NLS-2$//$NON-NLS-1$
				(yylength() + yychar) + "):\'" +//$NON-NLS-1$
					StringUtils.escape(yytext()) + "\'");//$NON-NLS-1$
		}
	}
	/* user method  - skeleton.sed */
	public final boolean isEOF() {
		return yy_atEOF;
	}
/* user method - skeleton.sed */
protected final boolean containsTagName(String markerTagName) {
	Iterator blocks = fBlockMarkers.iterator();
	while(blocks.hasNext()) {
		BlockMarker marker = (BlockMarker)blocks.next();
		if(marker.isCaseSensitive()) {
			if(marker.getTagName().equals(markerTagName))
				return true;
		}
		else {
			if(marker.getTagName().equalsIgnoreCase(markerTagName))
				return true;
		}
	}
	return false;
}

  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() {
    if (!yy_eof_done) {
      yy_eof_done = true;
    // do nothing, this is the downstream parser's job

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public String primGetNextToken() throws java.io.IOException {
    int yy_input;
    int yy_action;


    while (true) {

      yychar+= yylength();

      yy_action = -1;

      yy_currentPos = yy_startRead = yy_markedPos;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {
    
          yy_input = yy_advance();

          if ( yy_input == YYEOF ) break yy_forAction;

          int yy_next = yytrans[ yy_rowMap[yy_state] + yycmap[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = YY_ATTRIBUTE[yy_state];
          if ( (yy_attributes & 1) > 0 ) {
            yy_action = yy_state; 
            yy_markedPos = yy_currentPos; 
            if ( (yy_attributes & 8) > 0 ) break yy_forAction;
          }

        }
      }


      switch (yy_action) {    

        case 280: 
          { 
	if(Debug.debugTokenizer)
		dump("XSL processing instruction target");//$NON-NLS-1$
        yybegin(ST_XML_PI_ATTRIBUTE_NAME);
        return XML_TAG_NAME;
 }
        case 282: break;
        case 272: 
        case 274: 
        case 275: 
          { 
	if(Debug.debugTokenizer)
		dump("\nCDATA start");//$NON-NLS-1$
	fStateStack.push(yystate());
	yybegin(ST_CDATA_TEXT);
	return XML_CDATA_OPEN;
 }
        case 283: break;
        case 265: 
          { 
	if(Debug.debugTokenizer)
		dump("element");//$NON-NLS-1$
	yybegin(ST_XML_ELEMENT_DECLARATION);
	return XML_ELEMENT_DECLARATION;
 }
        case 284: break;
        case 264: 
          { 
	if(Debug.debugTokenizer)
		dump("attlist");//$NON-NLS-1$
	yybegin(ST_XML_ATTLIST_DECLARATION);
	return XML_ATTLIST_DECLARATION;
 }
        case 285: break;
        case 263: 
          { 
	if(Debug.debugTokenizer)
		dump("doctype");//$NON-NLS-1$
	yybegin(ST_XML_DOCTYPE_DECLARATION);
	return XML_DOCTYPE_DECLARATION;
 }
        case 286: break;
        case 258: 
          { 
	if(Debug.debugTokenizer)
		dump("doctype external id");//$NON-NLS-1$
	yybegin(ST_XML_DOCTYPE_ID_PUBLIC);
	return XML_DOCTYPE_EXTERNAL_ID_PUBLIC;
 }
        case 287: break;
        case 257: 
          { 
	if(Debug.debugTokenizer)
		dump("doctype external id");//$NON-NLS-1$
	yybegin(ST_XML_DOCTYPE_ID_SYSTEM);
	return XML_DOCTYPE_EXTERNAL_ID_SYSTEM;
 }
        case 288: break;
        case 226: 
          { 
	if(Debug.debugTokenizer)
		dump("\nCharRef");//$NON-NLS-1$
	return XML_CHAR_REFERENCE;
 }
        case 289: break;
        case 224: 
          { 
	if(Debug.debugTokenizer)
		dump("\ncomment start");//$NON-NLS-1$
	yybegin(ST_XML_COMMENT);
	return XML_COMMENT_OPEN;
 }
        case 290: break;
        case 204: 
        case 205: 
          { 
	if(Debug.debugTokenizer)
		dump("XML processing instruction target");//$NON-NLS-1$
        yybegin(ST_XML_PI_ATTRIBUTE_NAME);
        return XML_TAG_NAME;
 }
        case 291: break;
        case 203: 
          { 
	if(Debug.debugTokenizer)
		dump("comment end");//$NON-NLS-1$
	yybegin(YYINITIAL);
	return XML_COMMENT_CLOSE;
 }
        case 292: break;
        case 202: 
          { 
	if(Debug.debugTokenizer)
		dump("CDATA end");//$NON-NLS-1$
	yybegin(fStateStack.pop());
	return XML_CDATA_CLOSE;
 }
        case 293: break;
        case 201: 
          { 
	if(Debug.debugTokenizer)
		dump("\nPEReference");//$NON-NLS-1$
	return XML_PE_REFERENCE;
 }
        case 294: break;
        case 200: 
          { 
	if(Debug.debugTokenizer)
		dump("\nEntityRef");//$NON-NLS-1$
	return XML_ENTITY_REFERENCE;
 }
        case 295: break;
        case 193: 
        case 217: 
        case 222: 
          { 
	if(Debug.debugTokenizer)
		dump("\nFM start");//$NON-NLS-1$
	fStateStack.push(yystate());
	yybegin(ST_DIRECTIVE_TEXT);
	return FM_TAG_OPEN;
 }
        case 296: break;
        case 146: 
        case 160: 
        case 168: 
          { 
	return XML_DOCTYPE_INTERNAL_SUBSET;
 }
        case 297: break;
        case 134: 
          { 
        yybegin(YYINITIAL);
	if(Debug.debugTokenizer)
		dump("empty tag close");//$NON-NLS-1$
        return XML_EMPTY_TAG_CLOSE;
 }
        case 298: break;
        case 127: 
          { 
	if(Debug.debugTokenizer)
		dump("XML processing instruction end");//$NON-NLS-1$
        yybegin(YYINITIAL);
        return XML_PI_CLOSE;
 }
        case 299: break;
        case 126: 
          { 
		// ended with nothing inside
        yybegin(YYINITIAL);
        return XML_PI_CLOSE;
 }
        case 300: break;
        case 123: 
          { 
	if(Debug.debugTokenizer)
		dump("processing instruction end");//$NON-NLS-1$
        yybegin(YYINITIAL);
        return XML_PI_CLOSE;
 }
        case 301: break;
        case 114: 
          { 
	fStateStack.push(yystate());
	if(Debug.debugTokenizer)
		dump("\ndeclaration start");//$NON-NLS-1$
        yybegin(ST_XML_DECLARATION);
	return XML_DECLARATION_OPEN;
 }
        case 302: break;
        case 55: 
        case 57: 
        case 58: 
        case 59: 
        case 131: 
          { 
	if(Debug.debugTokenizer)
		dump("XML processing instruction attribute value");//$NON-NLS-1$
        yybegin(ST_XML_PI_ATTRIBUTE_NAME);
        return XML_TAG_ATTRIBUTE_VALUE;
 }
        case 303: break;
        case 54: 
          { 
	if(Debug.debugTokenizer)
		dump("XML processing instruction '='");//$NON-NLS-1$
        yybegin(ST_XML_PI_ATTRIBUTE_VALUE);
        return XML_TAG_ATTRIBUTE_EQUALS;
 }
        case 304: break;
        case 53: 
          { 
	if(Debug.debugTokenizer)
		dump("XML processing instruction attribute name");//$NON-NLS-1$
        yybegin(ST_XML_PI_EQUALS);
        return XML_TAG_ATTRIBUTE_NAME;
 }
        case 305: break;
        case 49: 
        case 50: 
        case 51: 
          { 
	// block scan until close is found
	return doScan("?>", false, XML_PI_CONTENT, ST_XML_PI_TAG_CLOSE, ST_XML_PI_TAG_CLOSE);
 }
        case 306: break;
        case 48: 
          { 
        yybegin(ST_PI_CONTENT);
        return WHITE_SPACE;
 }
        case 307: break;
        case 45: 
        case 46: 
        case 47: 
        case 124: 
        case 125: 
        case 230: 
        case 244: 
        case 253: 
        case 262: 
        case 269: 
        case 273: 
        case 276: 
        case 277: 
        case 278: 
        case 279: 
          { 
	if(Debug.debugTokenizer)
		dump("processing instruction target");//$NON-NLS-1$
        yybegin(ST_PI_WS);
        return XML_TAG_NAME;
 }
        case 308: break;
        case 40: 
        case 41: 
          { 
	if(Debug.debugTokenizer)
		dump("comment content");//$NON-NLS-1$
	return scanXMLCommentText();
 }
        case 309: break;
        case 39: 
          { 
	if(Debug.debugTokenizer)
		dump("LINE FEED");//$NON-NLS-1$
	return WHITE_SPACE;
 }
        case 310: break;
        case 34: 
        case 35: 
          { 
	if(Debug.debugTokenizer)
		dump("CDATA text");//$NON-NLS-1$
	String blockContext = doBlockScan("]]>", XML_CDATA_TEXT, ST_CDATA_END);//$NON-NLS-1$
	if(blockContext == XML_CDATA_TEXT)
		yybegin(ST_CDATA_END);
	return blockContext;
 }
        case 311: break;
        case 0: 
        case 30: 
        case 117: 
        case 118: 
        case 198: 
        case 199: 
        case 228: 
        case 229: 
        case 242: 
        case 243: 
          { 
	if(Debug.debugTokenizer)
		dump("\nXML content");//$NON-NLS-1$
	return XML_CONTENT;
 }
        case 312: break;
        case 5: 
        case 8: 
        case 9: 
        case 10: 
        case 13: 
        case 14: 
        case 15: 
        case 16: 
        case 17: 
        case 18: 
        case 19: 
        case 20: 
        case 21: 
        case 22: 
        case 24: 
        case 44: 
          { 
	if(Debug.debugTokenizer)
		dump("white space");//$NON-NLS-1$
        return WHITE_SPACE;
 }
        case 313: break;
        case 12: 
        case 61: 
          { 
	if(Debug.debugTokenizer)
		dump("inappropriate tag name");//$NON-NLS-1$
	yybegin(YYINITIAL);
        return XML_CONTENT;
 }
        case 314: break;
        case 23: 
        case 96: 
        case 97: 
        case 179: 
        case 180: 
        case 218: 
        case 238: 
        case 250: 
        case 259: 
        case 266: 
        case 270: 
          { 
	if(Debug.debugTokenizer)
		dump("elementdecl contentspec");//$NON-NLS-1$
	return XML_ELEMENT_DECL_CONTENT;
 }
        case 315: break;
        case 25: 
        case 103: 
        case 104: 
        case 191: 
        case 192: 
        case 223: 
        case 240: 
        case 251: 
        case 260: 
        case 267: 
        case 271: 
          { 
	if(Debug.debugTokenizer)
		dump("attlist contentspec");//$NON-NLS-1$
	return XML_ATTLIST_DECL_CONTENT;
 }
        case 316: break;
        case 31: 
        case 62: 
        case 73: 
          { 
	if(Debug.debugTokenizer)
		dump("\nstart tag open");//$NON-NLS-1$
        yybegin(ST_XML_TAG_NAME);
        return XML_TAG_OPEN;
 }
        case 317: break;
        case 32: 
        case 36: 
        case 37: 
        case 38: 
        case 42: 
        case 43: 
        case 52: 
        case 56: 
        case 60: 
        case 64: 
        case 70: 
        case 75: 
        case 76: 
        case 77: 
        case 78: 
        case 80: 
        case 81: 
        case 83: 
        case 88: 
        case 93: 
        case 100: 
          { 
	if (Debug.debugTokenizer)
		System.out.println("!!!unexpected!!!: \"" + yytext() + "\":" + //$NON-NLS-2$//$NON-NLS-1$
			yychar + "-" + (yychar + yylength()));//$NON-NLS-1$
	return UNDEFINED;
 }
        case 318: break;
        case 33: 
        case 119: 
          { 
	if(Debug.debugTokenizer)
		dump("non-reference %");//$NON-NLS-1$
	return XML_CONTENT;
 }
        case 319: break;
        case 63: 
          { 
	if(Debug.debugTokenizer)
		dump("tag close");//$NON-NLS-1$
	if(isBlockMarker()) {
        	yybegin(ST_BLOCK_TAG_SCAN);
	}
	else
        	yybegin(YYINITIAL);
        return XML_TAG_CLOSE;
 }
        case 320: break;
        case 65: 
        case 66: 
          { 
	if(Debug.debugTokenizer)
		dump("tag name");//$NON-NLS-1$
        yybegin(ST_XML_ATTRIBUTE_NAME);
        return XML_TAG_NAME;
 }
        case 321: break;
        case 67: 
          { 
	if(Debug.debugTokenizer)
		dump("attr name");//$NON-NLS-1$
        yybegin(ST_XML_EQUALS);
        return XML_TAG_ATTRIBUTE_NAME;
 }
        case 322: break;
        case 68: 
          { 
	if(Debug.debugTokenizer)
		dump("equals");//$NON-NLS-1$
        yybegin(ST_XML_ATTRIBUTE_VALUE);
        return XML_TAG_ATTRIBUTE_EQUALS;
 }
        case 323: break;
        case 69: 
        case 71: 
        case 72: 
        case 138: 
          { 
	if(Debug.debugTokenizer)
		dump("attr value");//$NON-NLS-1$
        yybegin(ST_XML_ATTRIBUTE_NAME);
        return XML_TAG_ATTRIBUTE_VALUE;
 }
        case 324: break;
        case 74: 
          { 
	if(Debug.debugTokenizer)
		dump("declaration end");//$NON-NLS-1$
	if (Debug.debugTokenizer) {
		if(fStateStack.peek()!=YYINITIAL)
			System.out.println("end embedded region");//$NON-NLS-1$
	}
	yybegin(fStateStack.pop());
	return XML_DECLARATION_CLOSE;
 }
        case 325: break;
        case 79: 
          { 
	if(Debug.debugTokenizer)
		dump("doctype type");//$NON-NLS-1$
	yybegin(ST_XML_DOCTYPE_EXTERNAL_ID);
	return XML_DOCTYPE_NAME;
 }
        case 326: break;
        case 82: 
        case 84: 
        case 85: 
        case 86: 
        case 152: 
        case 153: 
        case 156: 
        case 157: 
        case 212: 
          { 
	if(Debug.debugTokenizer)
		dump("doctype public reference");//$NON-NLS-1$
	yybegin(ST_XML_DOCTYPE_ID_SYSTEM);
	return XML_DOCTYPE_EXTERNAL_ID_PUBREF;
 }
        case 327: break;
        case 87: 
        case 89: 
        case 90: 
        case 91: 
        case 164: 
          { 
	if(Debug.debugTokenizer)
		dump("doctype system reference");//$NON-NLS-1$
	yybegin(ST_XML_DECLARATION_CLOSE);
	return XML_DOCTYPE_EXTERNAL_ID_SYSREF;
 }
        case 328: break;
        case 92: 
        case 94: 
        case 95: 
        case 172: 
        case 173: 
        case 176: 
        case 177: 
        case 215: 
          { 
	if(Debug.debugTokenizer)
		dump("elementdecl name");//$NON-NLS-1$
	yybegin(ST_XML_ELEMENT_DECLARATION_CONTENT);
	return XML_ELEMENT_DECL_NAME;
 }
        case 329: break;
        case 98: 
          { 
	if(Debug.debugTokenizer)
		dump("elementdecl close");//$NON-NLS-1$
	if (Debug.debugTokenizer) {
		if(fStateStack.peek()!=YYINITIAL)
			System.out.println("end embedded region");//$NON-NLS-1$
	}
	yybegin(fStateStack.pop());
	return XML_DECLARATION_CLOSE;
 }
        case 330: break;
        case 99: 
        case 101: 
        case 102: 
        case 184: 
        case 185: 
        case 188: 
        case 189: 
        case 220: 
          { 
	if(Debug.debugTokenizer)
		dump("attlist name");//$NON-NLS-1$
	yybegin(ST_XML_ATTLIST_DECLARATION_CONTENT);
	return XML_ATTLIST_DECL_NAME;
 }
        case 331: break;
        case 105: 
          { 
	if(Debug.debugTokenizer)
		dump("attlist close");//$NON-NLS-1$
	if (Debug.debugTokenizer) {
		if(fStateStack.peek()!=YYINITIAL)
			System.out.println("end embedded region");//$NON-NLS-1$
	}
	yybegin(fStateStack.pop());
	return XML_DECLARATION_CLOSE;
 }
        case 332: break;
        case 108: 
        case 109: 
          { 
	if(Debug.debugTokenizer)
		dump("FM body text");//$NON-NLS-1$
	String blockContext = doBlockScan(">", FM_DIRECTIVE_TEXT, ST_DIRECTIVE_END);//$NON-NLS-1$
	if(blockContext == FM_DIRECTIVE_TEXT)
		yybegin(ST_DIRECTIVE_END);
	return blockContext;
 }
        case 333: break;
        case 110: 
          { 
	if(Debug.debugTokenizer)
		dump("FM end");//$NON-NLS-1$
	yybegin(fStateStack.pop());
	return FM_TAG_CLOSE;
 }
        case 334: break;
        case 111: 
          { 
	if(Debug.debugTokenizer)
		dump("\nend tag open");//$NON-NLS-1$
        yybegin(ST_XML_TAG_NAME);
        return XML_END_TAG_OPEN;
 }
        case 335: break;
        case 112: 
          { 
	if(Debug.debugTokenizer)
		dump("\nprocessing instruction start");//$NON-NLS-1$
	yybegin(ST_PI);
        return XML_PI_OPEN;
 }
        case 336: break;
        case 106: 
        case 107: 
          { 
		return doBlockTagScan();
	 }
        case 337: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              return null;
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }    


}
